#!/bin/bash
rm -f /opt/$1.conf
cp /opt/template.conf /opt/$1.conf
echo "server_name $1 ;" >> /opt/$1.conf
echo "#listen 443 ssl http2;" >> /opt/$1.conf
echo "#ssl_certificate /root/.acme.sh/$1/fullchain.cer;" >> /opt/$1.conf
echo "#ssl_certificate_key /root/.acme.sh/$1/$1.key;" >> /opt/$1.conf
echo '}' >> /opt/$1.conf
cp /opt/$1.conf /etc/nginx/sites-enabled/
systemctl restart nginx
cd /root/.acme.sh && ./acme.sh --nginx --issue -d $1
sed -i 's/\#l/l/g' /etc/nginx/sites-enabled/$1.conf
sed -i 's/\#s/s/g' /etc/nginx/sites-enabled/$1.conf
sed -i 's/listen\ 80\;//g' /etc/nginx/sites-enabled/$1.conf
systemctl restart nginx
rm -f /opt/$1.conf
