#!/bin/bash
apt remove flussonic -y
rm -f /etc/apt/sources.list.d/flussonic.list;
echo "deb http://apt.flussonic.com binary/" > /etc/apt/sources.list.d/flussonic.list;
apt update
apt install -y flussonic=$1
systemctl enable flussonic
systemctl restart flussonic
