global
    maxconn 500000
    nbthread 10
    # nbproc 2
    # cpu-map 1 1
    # cpu-map 2 2
    # stats bind-process 2
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon
    tune.ssl.cachesize 10000
    # Default SSL material locations
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
    ssl-default-bind-options no-sslv3
    # tune.maxrewrite  16384
    # tune.bufsize     32768

defaults
    log     global
    mode    http
    option  httplog
    option  tcplog
    option  redispatch
    option  dontlognull
    option  accept-invalid-http-request
    option  accept-invalid-http-response
    timeout http-request 10s
    timeout http-keep-alive 2s
    timeout queue 5s
    timeout tunnel 2m
    timeout client-fin 1s
    timeout server-fin 1s
    timeout connect 4s
    timeout client  20s
    timeout server  30s
    retries 3
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

listen stats
    bind *:9999
    stats enable
    stats hide-version
    stats uri /haproxy?stats
    stats auth admin:admin123
    stats refresh 5s

# frontend main_front
   # bind *:8901
   # maxconn 200000
   # default_backend main_back
   # mode http

# backend main_back
# balance roundrobin
# server proxymain1 192.144.32.4:30000 check
# server proxymain2 192.144.32.4:30001 check
# server proxymain3 192.144.32.4:30002 check
# server proxymain4 192.144.32.4:30003 check
# server proxymain5 192.144.32.4:30004 check
# server proxymain6 192.144.32.4:30005 check

frontend s_front
   bind *:8900
   option httplog
   option forwardfor
   maxconn 500000
   default_backend s_back

backend s_back
    option forwardfor
    option http-server-close
server proxymain1 192.144.32.4:30000 check
server proxymain2 192.144.32.4:30001 check
server proxymain3 192.144.32.4:30002 check
server proxymain4 192.144.32.4:30003 check
server proxymain5 192.144.32.4:30004 check
server proxymain6 192.144.32.4:30005 check
